version: 2

models:

  - name: dim_products
    description: "Dimension contenant les informations descriptives des produits."

    columns:

      - name: product_id
        description: "Identifiant unique du produit."
        tests:
          - unique
          - not_null


  - name: dim_factories
    description: "Dimension contenant les informations descriptives des usines."

    columns:

      - name: factory_id
        description: "Identifiant unique de l'usine."
        tests:
          - unique
          - not_null
      
  - name: dim_date
    description: "Dimension calendrier utilisée pour les analyses temporelles."

    columns:

      - name: date_id
        description: "Date unique utilisée comme clé de dimension."
        tests:
          - unique
          - not_null